"""mig1

Revision ID: 5c57b7e405b9
Revises: 
Create Date: 2024-02-11 13:58:18.983970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c57b7e405b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=20), nullable=False),
    sa.Column('photo', sa.String(length=100), nullable=False),
    sa.Column('introduction', sa.String(length=800), nullable=False),
    sa.Column('landmarks', sa.String(length=800), nullable=False),
    sa.Column('cultural', sa.String(length=800), nullable=False),
    sa.Column('activities', sa.String(length=800), nullable=False),
    sa.Column('culinary', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('review_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('by', sa.String(length=50), nullable=False),
    sa.Column('review', sa.String(length=800), nullable=False),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.Column('f_name', sa.String(length=20), nullable=False),
    sa.Column('l_name', sa.String(length=20), nullable=False),
    sa.Column('is_admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('review')
    op.drop_table('location')
    # ### end Alembic commands ###
